### ISSUE TITLE
实现

### ISSUE THREAD

**Issue by zzhitnlper** [ianporada/mt5_coref_pytorch#1]
是Coreference Resolution through a seq2seq Transition-Based System的完整实现吗？不缺预测函数啥的把？按照readme进行仅能运行是吗？

**Comment by ianporada** [comment]
This implementation is mostly just a minimal example using the original scripts from the google repo. I've reimplemented the whole model inference and training as part of another project (https://arxiv.org/abs/2404.00727). I can add documentation and code sometime tomorrow

**Comment by ianporada** [comment]
Here's an example how to run inference on an entire dataset using our reimplementation: https://github.com/ianporada/coref-reeval/tree/main/models/LinkAppend
